#### Introduction to python programming 

In [1]:
# Variable Definition
number = 100        #Defining Integer Variable
decimal = 1000.890  #Defining Float Variable : Decimal Values 
string = 'Hello World' #Defining String: "Text Information"
'''
Data types in python are as follows:
1.Integer
2.Float
3.string
'''



'\nData types in python are as follows:\n1.Integer\n2.Float\n3.string\n'

In [2]:
# Checking Datatype Variables
print(type(number))
print(type(decimal))
print(type(string))



<class 'int'>
<class 'float'>
<class 'str'>


In [3]:
# type casting of data type
num = 100.2908383  #Datatype  :Float 
print(int(num))    #float is typecasted to int

100


In [ ]:
# Using input function
# input() :--> Function
num =input('Enter the value')
'''
Whenever we use input function, the output of input function is always string
'''

print(type(num))
#doing typecasting
print(int(num))   #Typecasting string value to integer
print(float(num)) #typecasting string value to float


In [ ]:
# Ask the user ro enter the string using input finction

str =input('Enter the name of the person: ')
print('tousif',str)
print(type(str))

tousif 20
<class 'str'>


In [ ]:
# perform Mathmatical Operation 
num1 = float(input('Enter the first Number'))
num2 = float(input('Enter the second Number'))

num3 = num1 + num2

#using fstring method 
print(f'the addition of two number as {num1} and{num2} is',num3)


ValueError: could not convert string to float: ''

In [ ]:
#Strings Indexing and Slicing

string = input('Enter the string')

'''
H e l l o   W o r l d
0 1 2 3 4 5 6 7 8 9 10    :L--->R
...............-3-2-1     :R-->L
'''
print(string[6])   #Indexing
print(string[-5])  #Indexing

IndexError: string index out of range

In [ ]:
# Concept of Slicing
string = input('Enter the string')
'''
string[start:stop]
Example:
string = Hello World
string = Hello World
string[1:4]  ---> o/p :ell
'''
print(string[1:4])
print(string[:-1])
print(string[2:2])
print(string[4:-1])


ell
Hello World

o World


In [ ]:
# Concept of Slicing
string = input('Enter the string')
'''
string[start:stop:step]
Example:
string = Hello World
string = Hello World
string[1:4]  ---> o/p :ell
'''
print(string[1::2])

el ol


In [ ]:
#concept of Indexing and Slicing Together
str = 'Hello welcome to the world of python programming'
print(str[::2])
print(str[4:-2:])
print(str[::-1])

Hlowloet h ol fpto rgamn
o welcome to the world of python programmi
gnimmargorp nohtyp fo dlrow eht ot emoclew olleH


In [ ]:
# Data Structures in python programming

'''
1. List : []  . Mutable in Nature
2. Tuple :() . Immutable in Nature
3. Dictionary : {'key1':Value, 'key2',Value2} : Immutable in Nature
4. sets  : {1,2,3,4,5} : Immutable in Nature
'''
# if Your are performming any computational software development program tuple is most preferred
# List Definition 

lst = [10,20,30,40]
print(lst)
print(type(lst))
# append() this is function which defined in class list 
# Therefore, append() is a method of class list 
# lst. append(50) :you are calling function using. operator
lst.append(50)
print(lst)

[10, 20, 30, 40]
<class 'list'>
[10, 20, 30, 40, 50]


In [ ]:
lst.insert(0,50) # This function will add the value 50 at an index 0   
print(lst)

[50, 50, 50, 5, 10, 20, 30, 40, 50]


In [ ]:
lst.count(50)  #This function will count of values 

4

In [ ]:
lst.pop()  #This function will remove the last number present in the list
print(lst)

[50, 50, 50, 5, 10, 20, 30]


In [ ]:
lst.remove(50) #This function will remove the specified value
print(lst)

[50, 50, 5, 10, 20, 30]


In [ ]:
lst = [10,10,20,30,40,50,70,80]
lst.pop()
lst.remove(10)
lst.remove(20)
lst.remove(50)
print(lst)

[10, 30, 40, 70]


In [ ]:
#Calculate length of the number present in list
#len() :function
print(len(lst))

4


In [ ]:
#concept of Indexing and Slicing on List 
lst = [10,20,30,40,50,60]
print(lst[0::2])
print(lst[::-1])
print(lst[2])


[10, 30, 50]
[60, 50, 40, 30, 20, 10]
30


In [ ]:
#Example 1
lst= [10,20,30,[40,50,60],[1,[2,[3,4,5,6],7],8,9],10]


In [ ]:
#o/p :5
lst[4][1][1][2]

5

In [ ]:
# Example 2
lst = [10,20,[1,2,3,[10,20,[30,[40,50,[60],70],90],9,100],1000],2000,[10000]]

In [ ]:
# O/P :60
lst[2][3][2][1][2][0]

60

In [ ]:
#Example 3
lst = [10,[100,200,300,[400,[500,[[[600],700],1],10],20]]]

In [ ]:
lst[1][3][1][1][0][0][0]

600

In [ ]:
# Example 4
# o/p : [800,900,1000]
lst=[10,[100,200,300,[400,[500,[[[600,700,800,900,1000,1100,1200],700],1],10],20]]]
lst[1][3][1][1][0][0][2:5]

[800, 900, 1000]

In [ ]:
# Tuple Definition 
tuple = (10,20,30,40)
print(type(tup))
tup.count(10)

<class 'tuple'>


1

In [ ]:
tuple.index(10)

0

In [ ]:
#tuple indexing and slicing 
tuple = (10,20,30,[40,50,(30,40,(60,70,80))])

In [ ]:
# Example :
#o/p70:80

tuple [3][2][2][1:]

(70, 80)

In [ ]:
# Conditional statement
'''
if condition==True:
perform operation inside the loop
els:
perform this  operation 
note:= :Assignment operator
== : comparison operator
'''
num = 10

if num ==10:
    print('The value is 10')
else :
    print('The value is not 10')
        

The value is 10


In [ ]:
# check the given string is palindrom or not 

text ='dad'
text1 = text[::-1]

if text == text1:
    print('The given string is palindrom')
else: 
    print('The givenn string is not a palindrom')

The given string is palindrom


In [ ]:
'''
if condition:
statement 
elif condition:
statement 
else:
statement
'''

'\nif condition:\nstatement \nelif condition:\nstatement \nelse:\nstatement\n'

In [ ]:
''' 
marks >80 : Best student 
marks between 60 to 79 :Good student 
marks between 50 to 59 :Average student 
marks< 49 : poor student 
'''

marks = float(input('Enter Marks of the student: '))

if marks >= 80:
    print ('Best student')
elif marks <80 and marks > 60:
    print('Good student')
elif marks <60 and marks > 50:
    print ('Average student')
else:
    print('poor student')

poor student


In [ ]:
''' 
Balance = 10000
Withdraw = amount
threshould = 2000
'''

balance = 10000
threshould = 2000
withdraw = float(input('Enter the amout to withdraw'))

if withdraw >= balance:
    print('insufficient balance')
if withdraw <= balance:
    new_balance =balance - withdraw
if new_balance >= 2000:
    print('New balance is',new_balance)
else:
    print('check your transaction, once again')

check your transaction, once again


In [ ]:
# For Loop 
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
for i in range (1,11):
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 10 

In [ ]:
''' 
*
**
***
****
*****
'''
for i in range(1,6):
    print('*'*i,) 

*
**
***
****
*****


In [ ]:
for i in range(1,6):
    print('*'*i*i)

*
****
*********
****************
*************************


In [ ]:
# for loop 
list= []
for i in range (0,10):
    list.append(i*i)
    print(list)

[0]
[0, 1]
[0, 1, 4]
[0, 1, 4, 9]
[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16, 25]
[0, 1, 4, 9, 16, 25, 36]
[0, 1, 4, 9, 16, 25, 36, 49]
[0, 1, 4, 9, 16, 25, 36, 49, 64]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
# list comprehension 
# variable = [expression for count in range(x1,x2)]
square = [i*1 for i in range(0,10)]
square

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
odd = [i%2 == 1 for i in range(0,10)]
odd

[False, True, False, True, False, True, False, True, False, True]

In [ ]:
square = [i**2 for i in range (0,10)]
square

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
lst = ['Aniket','Parag','Nikhil','Mihir','Tanvi','Ajay']
new_list = [lst.upper() for lst in lst]
new_list

['ANIKET', 'PARAG', 'NIKHIL', 'MIHIR', 'TANVI', 'AJAY']

In [ ]:
new_list = [lst.lower() for lst in lst]
new_list

['aniket', 'parag', 'nikhil', 'mihir', 'tanvi', 'ajay']

In [ ]:
new_list = [len(lst) for lst in lst]
new_list

[6, 5, 6, 5, 5, 4]

In [ ]:
new_list = sum([len(lst) for lst in lst])
new_list

31

In [ ]:
new_list = min([len(lst) for lst in lst])
new_list

4

In [ ]:
new_list = max([len(lst) for lst in lst])
new_list

6

In [ ]:
#Logic 0 2 4 6 8: sum :20
n = sum([x for x in range (0,10) if x %2==0])
n

20

In [ ]:
#Logic 0 1 3 5 7 9: sum :25
n = sum([x for x in range (0,10) if x %2 != 0])
n

25

In [ ]:
#5 ! 5*4*3*2*1  ---> 120 
import math
math.factorial(5)

120

In [ ]:
# square root 
print(5**0.5)
print(math.sqrt(5))

2.23606797749979
2.23606797749979


In [ ]:
# pow 

print(math.pow(2,2))

4.0


In [ ]:
print(math.log10(10))

1.0


In [ ]:
import math 
import os
import datetime


In [ ]:
# define function 

def sum(): #sum() function definition 
    print('HELLO WORLD')
    
ans = sum() #sum() function calling and storing in variable ans

HELLO WORLD


In [ ]:
def sum(num1,num2):
    num3 = num1 + num2
    print(num3)
    
ans = sum(100,200)

300


In [ ]:
def sum(num1,num2):
    num3 = num1 + num2
    print(F'The Addition of two number{num1} and {num2} is',num3) 
    
ans = sum(100,200)

The Addition of two number100 and 200 is 300


In [ ]:
num1 = float(input('Enter the first number'))
num2 = float(input('Enter the second number'))

def sum(num1,num2):
    num3 = num1 + num2
    print(f'The Addition of two number{num1} and {num2} is',num3)
    return num3
    
def mul(num1,num2):
    num4 = num1 * num2
    print(f'The multiplication of two number{num1} and {num2} is',num4)
    return num4
    
addition = sum(num1,num2)
multiplication = mul(num1,num2)

The Addition of two number10.0 and 20.0 is 30.0
The multiplication of two number10.0 and 20.0 is 200.0


In [ ]:
multiplication

In [ ]:
''' 
palindrom :
mom = mom
'''
text = input('Enter the string: ')
text1 = text[::-1]

def pal(text):
    if text == text1:
        print('The given is string is palindrom.')
    else:
        print('The given string is not a palindrom')
    
pal(text)

The given is string is palindrom.


In [ ]:
''' 
CGPA >= 8 : Bright Student
CGPA between 6.9 to 7.9: Moderate student 
CGPA =< 6.8 : Weak student
'''

# Get CGPA input from user
cgpa = float(input("Enter your CGPA: "))

# Classification based on CGPA
if cgpa >= 8:
    print("Bright Student")
elif cgpa <= 7.9 and cgpa >= 6.9:
    print("Moderate Student")
else:
    print("Weak Student")




Moderate Student


In [ ]:
cgpa = float(input("Enter your CGPA: "))

def compute(cgpa):
    if cgpa >= 8:
        print("Bright Student")
    elif cgpa <= 7.9 and cgpa >= 6.9:
        print("Moderate Student")
    else:
        print("Weak Student")
    
compute(cgpa)

Moderate Student


In [ ]:
text = input('Enter the text: ')
text1 = text[::-1]
def  palindrom(text):   #Defining Function
    global text1
    if text == text1:
        print('The given string is palindrom: ')
    else:
        print('The given string is not a palindrom: ')
        
palindrom(text)    # Calling a function 

The given string is palindrom: 


In [ ]:
# Recurssive Function 
# 5! = 5*4*3*2*1 =120

def  factorial(n):
    if n == 0 or n == 1:
        return 1 # base case 
    else:
        return n* factorial(n-1)
    
factorial(5)

120

In [ ]:
# oop: Object oriented programming 

class ClassName:
    i=12345
    
x = ClassName()
x.i

12345

In [ ]:
class Complex: #ClassName: Complex
    def __init__(self,real,img):        #Constuctor method
        self.r = real                   #Attribute
        self.i = img                    #Attribute
x = Complex(10,10)   #x is an object of class complex
x.r  # Calling Attribute using dot operator with the help of object x
x.i  # Calling Attribute using dot operator with the help of object x
print(x.r,'+',x.i,'j')

10 + 10 j


In [ ]:
class addition:
    def __init__(self):
        self.num1 = 100
        self.num2 = 200 
    def sum(self):
        num3 = self.num1 + self.num2
        return num3

a = addition()
a.sum()

300

In [ ]:
# Concept of INHERITANCE
# Parent class
class Car:
    def __init__(self,brand,model):
        self.brand = brand
        self.model = model
    
    def start(self):
        print(f"{self.brand} {self.model} is starting...")

    def stop(self):
        print(f"{self.brand} {self.model} is stopping...")

# Child class
class ElectricCar(Car):
    def __init__(self,brand,model,battery_capacity):
        super().__init__(brand,model) # Inherit barnd and model
        self.battery_capacity = battery_capacity

    def charge(self):
        print(f"{self.brand} {self.model} is charge with {self.battery_capacity} KWh battery.")

# Create an object of ElectricCar
tesla = ElectricCar("Tesla","Model S",10000)
tesla.start()
tesla.charge()
tesla.stop()

Tesla Model S is starting...
Tesla Model S is charge with 10000 KWh battery.
Tesla Model S is stopping...


In [ ]:
class Car:
    def start_engine(slef):
        print("starting engine...")
        
class ElectricCar(Car):
    def start_engine(self):
        print("starting silent electric engine...")
        
#Child class
class petrolCar(Car):
    def start_engine(slef):
        print("starting petrol engine with sound...")
        


In [ ]:
object1 = Car()    #Object is defined with parent class 
object2 = ElectricCar() #Object is defined with child class
object3 = petrolCar()    #Object is defined with child class

In [ ]:
object1.start_engine()

starting engine...


In [ ]:
object2.start_engine()

starting silent electric engine...


In [ ]:
object3.start_engine()

starting petrol engine with sound...


In [ ]:
# Defining parent class: Bank_Account
class Bank_Account:
    # Defining special method: Constructor function
    def _init_(self):
        # Defining attributes inside constructor function
        self.first_name = input('Enter the first_name') 
        self.last_name = input('Enter the last_name')
        self.age = int(input('Enter the age'))
        self.sex = input('Enter the sex')
        self.mobile_number = int(input('mobile_number'))
    # Defining method: details
    def details(self):
        print(f'The first name is {self.first_name}')
        print(f'The last name is {self.last_name}')
        print(f'The age is {self.age}')
        print(f'The sex is {self.sex} ')
        print(f'The mobile number is {self.mobile_number}')

# Defining Child Class: Saving_Acc 
class Saving_Acc(Bank_Account):
    # Defing method: intrest rate
    def intrest_rate(self):
        return 3
    
# Defining Child Class:Current_Acc  
class Current_Acc(Bank_Account):
    # Defing method: intrest rate
    def intrest_rate(self):
        return 0
    
# Defining Child Class:Pensioner_acc
class Pensioner_acc(Bank_Account):
    # Defing method: intrest rate
    def intrest_rate(self):
        return 6
    
# Defining Child Class:NRI_Acc  
class NRI_Acc(Bank_Account):
    # Defing method: intrest rate
    def intrest_rate(self):
        return 5 
    
# Defining Object
Mihir = Saving_Acc()
Disha = Current_Acc()
Ajay = Pensioner_acc()
Nikhil = NRI_Acc()
Aniket = Saving_Acc()
Parag = Current_Acc()
Tosif = Pensioner_acc()
Hemangi = NRI_Acc()

In [ ]:
Mihir.intrest_rate()

3

In [3]:
#1D Array 
arr = [1,2,3,4,5]
print(type(arr))


<class 'list'>


In [4]:
arr.append(6)

In [5]:
arr

[1, 2, 3, 4, 5, 6]

In [6]:
# Numpy Array Formation 

import numpy as np 
arr = np.array(arr)
print(arr.ndim)   #n Dimensions
print(arr.shape)  # Dataset Shape: rows,columns
print(arr)        # Print : Array

1
(6,)
[1 2 3 4 5 6]


In [7]:
#2D array 

arr1 = [[1,2,3],[4,5,6]]
arr1 = np.array(arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1)

2
(2, 3)
[[1 2 3]
 [4 5 6]]


In [8]:
#3D Array

arr2 = [[[1,2,3,],[4,5,6]]]
arr2 = np.array(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2)

3
(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]


In [ ]:
#Matrix summation 

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

c = a+b
print(c)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [ ]:
# diagonal matrix

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
c = np.eye(3)

d = a + c 
print(d)


[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]


In [9]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
c = np.eye(3)
d = np.zeros(3)
e = np.ones(3)

z = b+e
print(z)

[[11. 21. 31.]
 [41. 51. 61.]
 [71. 81. 91.]]


In [10]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [12]:
a/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [13]:
a*[2,3,4]


array([[ 2,  6, 12],
       [ 8, 15, 24],
       [14, 24, 36]])

In [14]:
# Changing Dtype :Datatype

a = np.array([1,2,3],dtype = 'float')
print (a)

[1. 2. 3.]


In [15]:
a = np.array([0,2,3], dtype = 'bool')
a

array([False,  True,  True])

In [16]:
a = np.array([0,2,3],dtype = 'complex')
a

array([0.+0.j, 2.+0.j, 3.+0.j])

In [17]:
# Arange Function 
# np.arange(start,stop,step)

a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [18]:
num = np.arange(0,20)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
num.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [20]:
num.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [21]:
num.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [22]:
np.linspace(1,10,8)

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [23]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [24]:
a = np.linspace(0,20,10)
print(a.size)
a

10


array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [26]:
num = np.arange(0,30)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [27]:
arr = num.reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [28]:
arr.max(),arr.min(),arr.mean(),arr.std()

(29, 0, 14.5, 8.65544144839919)

In [29]:
n = np.arange(50,100) #1D
m = n.reshape(10,5)  #2D
print(m.ndim)  #checking dimension :2D
m[1:3,1:3]
m

2


array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [30]:
m[6:9,1:4]

array([[81, 82, 83],
       [86, 87, 88],
       [91, 92, 93]])

In [49]:
n = np.arange(101,131,dtype='float')
o = n.reshape(1,6,5) #3D
print(o.ndim) #checking Dimension :3D
o

3


array([[[101., 102., 103., 104., 105.],
        [106., 107., 108., 109., 110.],
        [111., 112., 113., 114., 115.],
        [116., 117., 118., 119., 120.],
        [121., 122., 123., 124., 125.],
        [126., 127., 128., 129., 130.]]])

In [50]:
#Slicing
o[3:,3:]

array([], shape=(0, 3, 5), dtype=float64)